Update .push-helm-chart.yml

diff --git a/.github/workflows/.push-helm-chart.yml b/.github/workflows/.push-helm-chart.yml
--- a/.github/workflows/.push-helm-chart.yml
+++ b/.github/workflows/.push-helm-chart.yml
@@ -89,13 +89,14 @@ jobs:
           ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
           path: 'target-repo'
 
-      - name: Create new branch or checkout existing branch in target repository
+      - name: Create or Checkout Existing Branch in Target Repository
         run: |
           cd target-repo
           BRANCH_NAME="update-helm-chart-${{ env.package_tag }}"
+          git fetch origin
           if git rev-parse --verify origin/$BRANCH_NAME; then
             git checkout $BRANCH_NAME
-            git pull origin $BRANCH_NAME
+            git merge origin/$BRANCH_NAME -X ours
           else
             git checkout -b $BRANCH_NAME
           fi
@@ -116,7 +117,7 @@ jobs:
           git config --global user.name "${{ vars.GLOBAL_USER}}"
           git config --global user.email "${{ vars.GLOBAL_EMAIL}}"
           git add .
-          git commit -m "update helm chart ${{ inputs.tag }}"
+          git commit -m "update helm chart ${{ inputs.tag }}" || true  # Avoids failure if there's nothing to commit
           git push --set-upstream origin update-helm-chart-${{ inputs.tag }}
 
       - name: Create Pull Request
